environment:
  global:
    PROJECT_NAME: rocket

  matrix:
      - TARGET: x86_64-pc-windows-gnu
        CHANNEL: stable
      - TARGET: i686-pc-windows-gnu
        CHANNEL: stable
      - TARGET: x86_64-pc-windows-gnu
        CHANNEL: beta
      - TARGET: i686-pc-windows-gnu
        CHANNEL: beta

# Based on https://github.com/japaric/rust-everywhere/blob/master/appveyor.yml
install:
  # Install Rust and Cargo
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

  # Add GCC to PATH if needed.
  - if "%TARGET%" == "i686-pc-windows-gnu" set PATH=%PATH%;C:\msys64\mingw32\bin
  - if "%TARGET%" == "x86_64-pc-windows-gnu" set PATH=%PATH%;C:\msys64\mingw64\bin

# 'cargo test' takes care of building for us, so disable Appveyor's build stage. This prevents
# the "directory does not contain a project or solution file" error.
# source: https://github.com/starkat99/appveyor-rust/blob/master/appveyor.yml#L113
build: false

# Equivalent to Travis' `script` phase
test_script:
  - cargo build --verbose
